# Generated by Django 4.1.6 on 2023-04-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Описание"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(verbose_name="Температура")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата измерения"
                    ),
                ),
                (
                    "image_model",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="images/"
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="measurement.sensor",
                        verbose_name="Модель датчика",
                    ),
                ),
            ],
        ),
    ]
