# Generated by Django 4.1.6 on 2023-04-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={
                "ordering": ["sensor", "date"],
                "verbose_name": "Новые замеры",
                "verbose_name_plural": "Измерения",
            },
        ),
        migrations.RemoveField(
            model_name="measurement",
            name="image_model",
        ),
    ]
