# Generated by Django 4.1.6 on 2023-04-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_alter_measurement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={},
        ),
        migrations.AddField(
            model_name="measurement",
            name="image_model",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="images/"
            ),
        ),
    ]
