# Generated by Django 4.1.6 on 2023-04-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0003_alter_measurement_options_measurement_image_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="date",
            new_name="created_at",
        ),
    ]
